spring:
  datasource:
    url: jdbc:h2:mem:ninja
    driver-class-name: org.h2.Driver
    username: ninja
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  flyway:
    enabled: true
